#ifndef USER_ABI_H
#define USER_ABI_H

#define USER_SYSCALL_EXIT 1u
#define USER_SYSCALL_YIELD 2u
#define USER_SYSCALL_SLEEP 3u
#define USER_SYSCALL_ACCEL_MEMSET 4u
#define USER_SYSCALL_NOOP 5u

#define USER_SYSCALL_OK 0
#define USER_SYSCALL_ERR_UNKNOWN (-1)

#define USER_BENCH_SYSCALL_ITERATIONS 64u
#define USER_BENCH_ACCEL_ITERATIONS 1u
#define USER_BENCH_ACCEL_LEN 64u

#endif
