#ifndef USER_ABI_H
#define USER_ABI_H

#define USER_SYSCALL_EXIT 1u
#define USER_SYSCALL_YIELD 2u
#define USER_SYSCALL_SLEEP 3u
#define USER_SYSCALL_ACCEL_MEMSET 4u

#define USER_SYSCALL_OK 0
#define USER_SYSCALL_ERR_UNKNOWN (-1)

#endif
